<a href="https://colab.research.google.com/github/prashantmane091318/ML/blob/main/Titanic12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [ ]:
df_train=pd.read_csv("train.csv")

In [ ]:
df_test=pd.read_csv("test.csv")

In [ ]:
df_train.head()

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [ ]:
x_train=df_train.drop("Survived",axis=1)

In [ ]:
x_train_test=pd.concat([x_train,df_test],axis=0)

In [ ]:
x_train_test

PassengerId  Pclass  ... Cabin Embarked
0              1       3  ...   NaN        S
1              2       1  ...   C85        C
2              3       3  ...   NaN        S
3              4       1  ...  C123        S
4              5       3  ...   NaN        S
..           ...     ...  ...   ...      ...
413         1305       3  ...   NaN        S
414         1306       1  ...  C105        C
415         1307       3  ...   NaN        S
416         1308       3  ...   NaN        S
417         1309       3  ...   NaN        C

[1309 rows x 11 columns]

In [ ]:
def handle_na(df):
    for col in df.columns:
        if df[col].dtype=='O':
            df[col]=df[col].fillna(df[col].mode()[0].split(" ")[0])
        else:
            df[col]=df[col].fillna(df[col].mean())
    return df

In [ ]:
df1=handle_na(x_train_test)

In [ ]:
df1.drop(["PassengerId","Cabin"],axis=1,inplace=True)

In [ ]:
def handle_encode(df):
    for col in df.columns:
        if df[col].dtype=="O":
            temp=pd.get_dummies(df[col],drop_first=True,prefix=col)
            df=pd.concat([df,temp],axis=1)
            df.drop(col,axis=1,inplace=True)
    return df
df2=handle_encode(df1)

In [ ]:
df1.drop("Name",axis=1,inplace=True)

In [ ]:
df1.drop("Ticket",axis=1,inplace=True)

In [ ]:
df2=handle_encode(df1)

In [ ]:
d=df2.columns

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
scaler=StandardScaler()

In [ ]:
df2_scaled=scaler.fit_transform(df2)

In [ ]:
df3=pd.DataFrame(df2_scaled,columns=d)

In [ ]:
df3.head()

Pclass       Age     SibSp  ...  Sex_male  Embarked_Q  Embarked_S
0  0.841916 -0.611972  0.481288  ...  0.743497    -0.32204    0.655011
1 -1.546098  0.630431  0.481288  ... -1.344995    -0.32204   -1.526692
2  0.841916 -0.301371 -0.479087  ... -1.344995    -0.32204    0.655011
3 -1.546098  0.397481  0.481288  ... -1.344995    -0.32204    0.655011
4  0.841916  0.397481 -0.479087  ...  0.743497    -0.32204    0.655011

[5 rows x 8 columns]

In [ ]:
x_train_final=df3.iloc[0:891]

In [ ]:
x_test_final=df3.iloc[891:]

In [ ]:
y=df_train["Survived"]

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
from xgboost import XGBClassifier

In [ ]:
param_test1 = {
 'max_depth':[9,10,11],
 'min_child_weight':[3,4,5],
 'n_estimators':[100,200,300,400]
}

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
model=XGBClassifier(learning_rate =0.1, gamma=0, subsample=0.8, colsample_bytree=0.8,
 objective= 'binary:logistic', nthread=4, scale_pos_weight=1, seed=27)

In [ ]:
grid=GridSearchCV(model,param_test1,cv=3,verbose=5,n_jobs=4)

In [ ]:
grid.fit(x_train_final_ns,y)

Fitting 3 folds for each of 36 candidates, totalling 108 fits


[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  10 tasks      | elapsed:    4.2s
[Parallel(n_jobs=4)]: Done  64 tasks      | elapsed:   20.4s
[Parallel(n_jobs=4)]: Done 108 out of 108 | elapsed:   35.0s finished


GridSearchCV(cv=3, error_score=nan,
             estimator=XGBClassifier(base_score=0.5, booster='gbtree',
                                     colsample_bylevel=1, colsample_bynode=1,
                                     colsample_bytree=0.8, gamma=0,
                                     learning_rate=0.1, max_delta_step=0,
                                     max_depth=3, min_child_weight=1,
                                     missing=None, n_estimators=100, n_jobs=1,
                                     nthread=4, objective='binary:logistic',
                                     random_state=0, reg_alpha=0, reg_lambda=1,
                                     scale_pos_weight=1, seed=27, silent=None,
                                     subsample=0.8, verbosity=1),
             iid='deprecated', n_jobs=4,
             param_grid={'max_depth': [9, 10, 11],
                         'min_child_weight': [3, 4, 5],
                         'n_estimators': [100, 200, 300, 400]},
          

In [ ]:
grid.estimator

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=0.8, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=4, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=27,
              silent=None, subsample=0.8, verbosity=1)

In [ ]:
model1=XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=0.8, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=4, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=27,
              silent=None, subsample=0.8, verbosity=1)

In [ ]:
model1.fit(x_train_final_ns,y)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=0.8, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=4, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=27,
              silent=None, subsample=0.8, verbosity=1)

In [ ]:
model1.score(x_train_final_ns,y)

0.8742985409652076

In [ ]:
yp=model1.predict(x_test_final_ns)

In [ ]:
yp

array([0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [ ]:
df=pd.DataFrame(df_test["PassengerId"])

In [ ]:
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [ ]:
df["Survived"]=yp1

In [ ]:
df.to_csv("Submission_titanic6698111.csv",index=False)

In [ ]:
x_train_final.columns

In [ ]:
x_train_final["Survived"]=y

In [ ]:
x_train_final.head()

In [ ]:
x_train_final.corr()["Survived"]

In [ ]:
x_train_final.drop("Survived",axis=1,inplace=True)

In [ ]:
x_train_final1=x_train_final.drop(["Parch","Embarked_Q"],axis=1)

In [ ]:
x_test_final1=x_test_final.drop(["Parch","Embarked_Q"],axis=1)

In [ ]:
x_train_final.head()

Pclass       Age     SibSp  ...  Sex_male  Embarked_Q  Embarked_S
0  0.841916 -0.611972  0.481288  ...  0.743497    -0.32204    0.655011
1 -1.546098  0.630431  0.481288  ... -1.344995    -0.32204   -1.526692
2  0.841916 -0.301371 -0.479087  ... -1.344995    -0.32204    0.655011
3 -1.546098  0.397481  0.481288  ... -1.344995    -0.32204    0.655011
4  0.841916  0.397481 -0.479087  ...  0.743497    -0.32204    0.655011

[5 rows x 8 columns]

In [ ]:
from sklearn.decomposition import PCA

In [ ]:
pca=PCA(n_components=3)

In [ ]:
pca.fit(x_train_final_ns)

PCA(copy=True, iterated_power='auto', n_components=3, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [ ]:
x_train_final_pca=pca.transform(x_train_final_ns)

In [ ]:
x_test_final_pca=pca.transform(x_test_final_ns)

In [ ]:
x_train_final_pca.shape

(891, 3)

In [ ]:
x_test_final_pca.shape

(418, 3)

PassengerId  Pclass  ... Cabin Embarked
0              1       3  ...   NaN        S
1              2       1  ...   C85        C
2              3       3  ...   NaN        S
3              4       1  ...  C123        S
4              5       3  ...   NaN        S
..           ...     ...  ...   ...      ...
886          887       2  ...   NaN        S
887          888       1  ...   B42        S
888          889       3  ...   NaN        S
889          890       1  ...  C148        C
890          891       3  ...   NaN        Q

[891 rows x 11 columns]

In [ ]:
df2

Pclass        Age  SibSp  ...  Sex_male  Embarked_Q  Embarked_S
0         3  22.000000      1  ...         1           0           1
1         1  38.000000      1  ...         0           0           0
2         3  26.000000      0  ...         0           0           1
3         1  35.000000      1  ...         0           0           1
4         3  35.000000      0  ...         1           0           1
..      ...        ...    ...  ...       ...         ...         ...
413       3  29.881138      0  ...         1           0           1
414       1  39.000000      0  ...         0           0           0
415       3  38.500000      0  ...         1           0           1
416       3  29.881138      0  ...         1           0           1
417       3  29.881138      1  ...         1           0           0

[1309 rows x 8 columns]

In [ ]:
x_train_final

Pclass       Age     SibSp  ...  Sex_male  Embarked_Q  Embarked_S
0    0.841916 -0.611972  0.481288  ...  0.743497   -0.322040    0.655011
1   -1.546098  0.630431  0.481288  ... -1.344995   -0.322040   -1.526692
2    0.841916 -0.301371 -0.479087  ... -1.344995   -0.322040    0.655011
3   -1.546098  0.397481  0.481288  ... -1.344995   -0.322040    0.655011
4    0.841916  0.397481 -0.479087  ...  0.743497   -0.322040    0.655011
..        ...       ...       ...  ...       ...         ...         ...
886 -0.352091 -0.223721 -0.479087  ...  0.743497   -0.322040    0.655011
887 -1.546098 -0.844922 -0.479087  ... -1.344995   -0.322040    0.655011
888  0.841916  0.000000  0.481288  ... -1.344995   -0.322040    0.655011
889 -1.546098 -0.301371 -0.479087  ...  0.743497   -0.322040   -1.526692
890  0.841916  0.164530 -0.479087  ...  0.743497    3.105202   -1.526692

[891 rows x 8 columns]

In [ ]:
x_train_final_ns=df2.iloc[0:891]

In [ ]:
x_test_final_ns=df2.iloc[891:]

In [ ]:
x_train_final

Pclass       Age     SibSp  ...  Sex_male  Embarked_Q  Embarked_S
0    0.841916 -0.611972  0.481288  ...  0.743497   -0.322040    0.655011
1   -1.546098  0.630431  0.481288  ... -1.344995   -0.322040   -1.526692
2    0.841916 -0.301371 -0.479087  ... -1.344995   -0.322040    0.655011
3   -1.546098  0.397481  0.481288  ... -1.344995   -0.322040    0.655011
4    0.841916  0.397481 -0.479087  ...  0.743497   -0.322040    0.655011
..        ...       ...       ...  ...       ...         ...         ...
886 -0.352091 -0.223721 -0.479087  ...  0.743497   -0.322040    0.655011
887 -1.546098 -0.844922 -0.479087  ... -1.344995   -0.322040    0.655011
888  0.841916  0.000000  0.481288  ... -1.344995   -0.322040    0.655011
889 -1.546098 -0.301371 -0.479087  ...  0.743497   -0.322040   -1.526692
890  0.841916  0.164530 -0.479087  ...  0.743497    3.105202   -1.526692

[891 rows x 8 columns]

In [ ]:
x_train_final.shape

(891, 8)

In [ ]:
y.shape

(891,)

In [ ]:
x_test_final.shape

(418, 8)

In [ ]:
import tensorflow as tf

In [ ]:
y_new=tf.keras.utils.to_categorical(y)

In [ ]:
y_new1=np.array(y_new)

In [ ]:
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [ ]:
model=tf.keras.models.Sequential()

In [ ]:
from tensorflow.keras.layers import Dense

In [ ]:
model.add(Dense(100,activation="linear",input_shape=(8,)))

In [ ]:
model.add(Dense(2,activation="softmax"))

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 100)               900       
_________________________________________________________________
dense_1 (Dense)              (None, 2)                 202       
_________________________________________________________________
dense_2 (Dense)              (None, 100)               300       
_________________________________________________________________
dense_3 (Dense)              (None, 2)                 202       
Total params: 1,604
Trainable params: 1,604
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(optimizer="adam",loss="categorical_crossentropy",metrics=["accuracy"])

In [ ]:
model.fit(x_train_final,y_new,batch_size=32,epochs=75)

Epoch 1/75
28/28 [==============================] - 0s 1ms/step - loss: 0.5823 - accuracy: 0.7666
Epoch 2/75
28/28 [==============================] - 0s 1ms/step - loss: 0.4445 - accuracy: 0.8462
Epoch 3/75
28/28 [==============================] - 0s 1ms/step - loss: 0.3972 - accuracy: 0.8429
Epoch 4/75
28/28 [==============================] - 0s 1ms/step - loss: 0.3778 - accuracy: 0.8519
Epoch 5/75
28/28 [==============================] - 0s 1ms/step - loss: 0.3711 - accuracy: 0.8485
Epoch 6/75
28/28 [==============================] - 0s 2ms/step - loss: 0.3645 - accuracy: 0.8519
Epoch 7/75
28/28 [==============================] - 0s 1ms/step - loss: 0.3629 - accuracy: 0.8496
Epoch 8/75
28/28 [==============================] - 0s 1ms/step - loss: 0.3606 - accuracy: 0.8507
Epoch 9/75
28/28 [==============================] - 0s 1ms/step - loss: 0.3620 - accuracy: 0.8541
Epoch 10/75
28/28 [==============================] - 0s 1ms/step - loss: 0.3583 - accuracy: 0.8575
Epoch 11/75
28/28 [

In [ ]:
model.evaluate(x_train_final,y_new)

28/28 [==============================] - 0s 1ms/step - loss: 0.3180 - accuracy: 0.8732


[0.3179905414581299, 0.8731762170791626]

In [ ]:
yp=model.predict(x_train_final)

In [ ]:
yp.argmax(axis=1)

array([0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,

In [ ]:
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [ ]:
yp1=model.predict(x_test_final)

In [ ]:
yp1=yp1.argmax(axis=1)

In [ ]:
yp1

array([0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [ ]:
yp

array([0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,